### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by tamalsaha** [coveo/wazuh-kubernetes#3]
Hi @JPLachance , thanks for open sourcing this. I have some question regarding this setup.

- Manager clients are run as StatefulSet. My understanding is that ossec clients are supposed to run on each node to scan logs and generate alerts. Should this be done using Statefulset?

- How does this scan logs for containers/pods, since those are not the /var/log folder on host?

- How does manager client register with the manager master ? Sometime ago I used wazuh's http api to do that on the fly. I remember that clients had to be registered in the client pods got restarted.

Thanks.

**Comment by JPLachance** [comment]
Hi @tamalsaha,

First of all, thanks for your interest in the project!

So, your first point about "manager clients" makes me think you are confused about differences between Wazuh manager client and Wazuh agent.
- A Wazuh manager client is a Wazuh manager, member of a Wazuh manager cluster, for which the `<cluster>` configuration contains `<node_type>client</node_type>` which means the manager is a client of another manager, the master manager.
- A Wazuh agent is an agent you should deploy on all your Kubernetes nodes.

To clarify those concepts, I updated the README of the project.
> This repository does not show how to deploy the Wazuh agent in a Kubernetes cluster. Normally, we would use a DaemonSet to deploy the agent on each Kubernetes node. To do that, we would need a Docker image with the Wazuh agent installed on it and then we would need to mount almost every folder of the host inside that container (`/bin`, `/etc`, `/var/log`, etc.). It would be a very complicated task since you cannot simply mount the `/bin` folder of your host in the `/bin` folder of your container. Therefore, creating such Docker image an using it in a Kubernetes DaemonSet is not the ideal way to deploy a Wazuh agent. Instead, you should take a look at the [Wazuh Ansible playbooks project](https://github.com/wazuh/wazuh-ansible) or at the [Wazuh Puppet module project](https://github.com/wazuh/wazuh-puppet) to deploy your Wazuh agents.

I hope it answers your first question 😃 

About your second question, Wazuh is not able to "scan logs for containers/pods". Even if you deploy a Wazuh agent for each of your Kubernetes node, you won't be able to see what is happening inside your containers running on your Kubernetes nodes. Wazuh in its basic configuration is only useful to monitor the host, not containers running on the host. You could always install the Wazuh agent on each of your containers, but it's not in Docker best practices to have multiple services running in a Docker container.

So, to see what is going on into your container in Kubernetes, you need something else. There are many options out there for you. A free and open source one is [Sysdig Falco](https://github.com/draios/falco). You can find the documentation on how to deploy Falco [here](https://github.com/draios/falco/tree/dev/examples/k8s-using-daemonset).

Finally, about your third question, I think again that question is due to a miss understanding of the difference between a Wazuh manager client and a Wazuh agent.

I hope this will help you. Wazuh is greate so secure an monitor suspicious activities on your hosts, but to monitor suspicious activities inside your container, you should look at other technologies out there. 

Have a nice day,

Jean-Philippe

**Comment by tamalsaha** [comment]
Thanks @JPLachance  for the detailed answer.

You are that right I confused this manager client with ossec agent. Do you know why would one use manager client (this seems like a scaling the manager type of thing)?

Regarding monitoring container logs, I think that is a necessary piece. I had an idea that we could potentially write a [FluentBit plugins](https://fluentbit.io/documentation/0.12/kubernetes/). This has built in support for how to go from pod to pod logs via Docker json log driver. 

Looking at the Sysdig Falco, I think those concers should be addressed by PodSecurityPoilcy. My understanding was that ossec was more for looking at file logs.

Lastly, I am new to these things. So, sorry if I am talking silly. :)

**Comment by tamalsaha** [comment]
https://github.com/kubernetes/kubernetes/blob/release-0.13/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf is what the original fluentd used to do. My understanding is that this is now rewritten as a C plugin.

**Comment by tamalsaha** [comment]
Most of the magic used to happen in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter plugin.

**Comment by JPLachance** [comment]
Hi @tamalsaha,

The reason why we use a StatefulSet of Wazuh manager client is for scalability and for high availability. The [Wazuh cluster deployment documentation](https://documentation.wazuh.com/3.x/user-manual/manager/wazuh-cluster.html) explains well the "why". This repository explains the "how" in Kubernetes.

Your solution of getting all the logs from containers using FluentBit could work. You would have to take all log files of all your containers, put them somewhere on the host then setup Wazuh to perform analysis on those paths. It look's complicated to me 😃

Instead of analyzing log files, Falco is analyzing system call as they are made. It can identify many suspicious behaviors inside your pods' containers and all that without having to setup Wazuh and FluentBit.

Anyway, on my side, I deployed a Wazuh manager cluster in Kubernetes, so it's easy to deploy and maintain.

So, are your original questions answered?

Have a nice weekend,

Jean-Philippe

**Comment by tamalsaha** [comment]
Thanks @JPLachance !
